### ISSUE TITLE
Error using Compile.m on Linux

### ISSUE THREAD

**Issue by nclprz** [CERN/TIGRE#11]
Hi!

I am trying to compile the toolbox on Ubuntu 64 bit, with cuda toolkit 7.5 installed and Matlab R2016a. 
In mex_CUDA_glnxa64.xml I have removed the "-gencode=arch=compute_13,code=sm_13" part under the NVCCFLAGS, since it was apparently not supported by my compiler and kept giving me errors (I have found this solution on an already closed issue here). The rest of mex_CUDA_glnxa64.xml was left unmodified, as the link to the cuda libraries seemed to be already correct.

When I try to run the Compile script, I am now returned this error:

> Error using mex
/usr/bin/ld: cannot find /usr/local/cuda-7.5/targets/x86_64-linux/lib: File format not recognized
collect2: error: ld returned 1 exit status

> Error in Compile (line 49)
        mex -largeArrayDims ./Source/Ax.cpp ./Source/ray_interpolated_projection.cu ./Source/Siddon_projection.cu
        ./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_parallel.cu -outdir ./Mex_files/linux64

Before that, I get a lot of warnings similar to the following one, all relative to Siddon_projection_parallel.cu

> /home/nicco/Downloads/TIGRE-1.1.1/./Source/Siddon_projection_parallel.cu(222): warning: variable "ku" was declared but never referenced

I have verified that the path to the cuda libraries in mex_CUDA_glnxa64.xml is correct. The folder /usr/local/cuda-7.5/targets/x86_64-linux/lib exists and contains .so files.

Any idea of what I am missing?

I apologize if the question turns out to be really obvious, but I am a complete beginner to Linux systems and on top of that I have never compiled any mex file!

**Comment by AnderBiguri** [comment]
Hi,
Unfortunately I don't have a access to a Linux machine now so I can not
test it.
Check again if all paths to NVIDIA are correct in the xml file (just in
case).
This could also be a matlab issue,  as they have been changing the paralel
computing toolbox in recent versions.
Try also compiling the following example : (run this line in matlab to open
it)

matlab:edit(fullfile(matlabroot,'toolbox','distcomp','gpu','extern','src','mex','mexGPUExample.cu'))

And see if you can.  It should be easier to compile this than Tigre.  If
you can't compile this,  it's something related to your local
configuration,  else Tigre may not be yet compatible with your system (and
of course we' ll fix that now!).
Let me know how that goes.
Ander

Hi!

I am trying to compile the toolbox on Ubuntu 64 bit, with cuda toolkit 7.5
installed and Matlab R2016a.
In mex_CUDA_glnxa64.xml I have removed the
"-gencode=arch=compute_13,code=sm_13"
part under the NVCCFLAGS, since it was apparently not supported by my
compiler and kept giving me errors (I have found this solution on an
already closed issue here). The rest of mex_CUDA_glnxa64.xml was left
unmodified, as the link to the cuda libraries seemed to be already correct.

When I try to run the Compile script, I am now returned this error:

Error using mex
/usr/bin/ld: cannot find /usr/local/cuda-7.5/targets/x86_64-linux/lib: File
format not recognized
collect2: error: ld returned 1 exit status

Error in Compile (line 49)
mex -largeArrayDims ./Source/Ax.cpp ./Source/ray_interpolated_projection.cu
./Source/Siddon_projection.cu
./Source/ray_interpolated_projection_parallel.cu ./Source/Siddon_projection_
parallel.cu -outdir ./Mex_files/linux64

Before that, I get a lot of warnings similar to the following one, all
relative to Siddon_projection_parallel.cu

/home/nicco/Downloads/TIGRE-1.1.1/./Source/Siddon_projection_parallel.cu(222):
warning: variable "ku" was declared but never referenced

I have verified that the path to the cuda libraries in mex_CUDA_glnxa64.xml
is correct. The folder /usr/local/cuda-7.5/targets/x86_64-linux/lib exists
and contains .so files.

Any idea of what I am missing?

I apologize if the question turns out to be really obvious, but I am a
complete beginner to Linux systems and on top of that I have never compiled
any mex file!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CERN/TIGRE/issues/11>, or mute the thread

**Comment by nclprz** [comment]
Hi,
thank you for the quick answer!
I can't compile that example, I get this error: 

> Error using mex
No supported compiler or SDK was found.

So I guess that the problem is with my local configuration. I have also tried on Windows, but I am receiving the same error when I try to compile that example (and of course the toolbox Compile.m doesn't work either).
I don't know much about compilers, I am using the one provided by default by Matlab. Do you have any other suggestions?

**Comment by AnderBiguri** [comment]
To make sure thaat you have the rigth compiler, go to

https://uk.mathworks.com/support/compilers/R2016a/index.html?sec=glnxa64

(you mentioned 2016a and Linux, else change)

And see if you have the rigth compiler isntalled. MATLAB  is very specific
about this, each MATLAB version and OS has very secific compilers that are
usable.

**Comment by nclprz** [comment]
I had gcc/g++ 4.8.4, but according to the page that you linked Matlab only supports 4.7.x (which should then be fine to compile everything except for Java...which I assume is not needed in this case?).
Therefore I have tried to get gcc/g++ 4.7 and force Matlab to use it. It has proven to be quite tricky, but I think that I have managed to set it now.
Of course, this hasn't solved the issue: if I try to compile the example, I get again this error

> Error using mex
/usr/bin/ld: cannot find /usr/local/cuda-7.5/targets/x86_64-linux/lib/: File format not recognized
collect2: error: ld returned 1 exit status

which is the one that I had when I tried the Compile.m script.

If it can be of any use, here is all of the verbose printout:

>  mex /usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/src/mex/mexGPUExample.cu -v
> 
> Verbose mode is on.
> Neither -compatibleArrayDims nor -largeArrayDims is selected.
> 	 Using -compatibleArrayDims. In the future, MATLAB will require the use of
> 	 -largeArrayDims and remove the -compatibleArrayDims option.
> 	 For more information:
> 	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.
> ... Looking for compiler 'nvcc' ...
> ... Looking for environment variable 'MW_NVCC_PATH' ...No.
> ... Executing command 'which nvcc' ...Yes ('/usr/local/cuda-7.5/bin/nvcc').
> ... Executing command 'which g++' ...Yes ('/usr/bin/g++').
> ... Executing command 'g++ -print-file-name=libstdc++.so' ...Yes ('/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so').
> Found installed compiler 'nvcc'.
> 
> Options file details
> 	Compiler location: /usr/local/cuda-7.5/bin/nvcc
> 	Options file: /home/nicco/Downloads/TIGRE-1.1.1/mex_CUDA_glnxa64.xml
> 	CMDLINE1 : /usr/local/cuda-7.5/bin/nvcc -c -DMX_COMPAT_32   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/usr/local/MATLAB/R2016a/extern/include" -I"/usr/local/MATLAB/R2016a/simulink/include" -I"/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include/" -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=\"sm_50,compute_50\" $NVCC_FLAGS --compiler-options=-ansi,-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread -O -DNDEBUG /usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/src/mex/mexGPUExample.cu -o /tmp/mex_12118211229821_9269/mexGPUExample.o
> 	CMDLINE2 : /usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2016a/extern/lib/glnxa64/mexFunction.map" /tmp/mex_12118211229821_9269/mexGPUExample.o   -Wl,-rpath-link,/usr/local/MATLAB/R2016a/bin/glnxa64 -L"/usr/local/MATLAB/R2016a/bin/glnxa64" -lmx -lmex -lmat -lm /usr/local/cuda-7.5/targets/x86_64-linux/lib/ -o mexGPUExample.mexa64
> 	CMDLINE3 : rm -f /tmp/mex_12118211229821_9269/mexGPUExample.o
> 	CXX : /usr/local/cuda-7.5/bin/nvcc
> 	DEFINES : -DMX_COMPAT_32   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE
> 	MATLABMEX : -DMATLAB_MEX_FILE
> 	NVCCFLAGS : -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=\"sm_50,compute_50\" $NVCC_FLAGS
> 	CXXFLAGS : --compiler-options=-ansi,-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread
> 	INCLUDE : -I"/usr/local/MATLAB/R2016a/extern/include" -I"/usr/local/MATLAB/R2016a/simulink/include" -I"/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include/"
> 	CXXOPTIMFLAGS : -O -DNDEBUG
> 	CXXDEBUGFLAGS : -g
> 	LDXX : /usr/bin/g++
> 	LDFLAGS : -pthread -Wl,--no-undefined 
> 	LDTYPE : -shared
> 	LINKEXPORT : -Wl,--version-script,"/usr/local/MATLAB/R2016a/extern/lib/glnxa64/mexFunction.map"
> 	LINKLIBS : -Wl,-rpath-link,/usr/local/MATLAB/R2016a/bin/glnxa64 -L"/usr/local/MATLAB/R2016a/bin/glnxa64" -lmx -lmex -lmat -lm /usr/local/cuda-7.5/targets/x86_64-linux/lib/
> 	LDOPTIMFLAGS : -O
> 	LDDEBUGFLAGS : -g
> 	OBJEXT : .o
> 	LDEXT : .mexa64
> 	NVCC : /usr/local/cuda-7.5/bin/nvcc
> 	GCC : /usr/bin/g++
> 	CPPLIB_DIR : /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so
> 	MATLABROOT : /usr/local/MATLAB/R2016a
> 	ARCH : glnxa64
> 	SRC : /usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/src/mex/mexGPUExample.cu
> 	OBJ : /tmp/mex_12118211229821_9269/mexGPUExample.o
> 	OBJS : /tmp/mex_12118211229821_9269/mexGPUExample.o 
> 	SRCROOT : /usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/src/mex/mexGPUExample
> 	DEF : /tmp/mex_12118211229821_9269/mexGPUExample.def
> 	EXP : mexGPUExample.exp
> 	LIB : mexGPUExample.lib
> 	EXE : mexGPUExample.mexa64
> 	ILK : mexGPUExample.ilk
> 	MANIFEST : mexGPUExample.mexa64.manifest
> 	TEMPNAME : mexGPUExample
> 	EXEDIR : 
> 	EXENAME : mexGPUExample
> 	OPTIM : -O -DNDEBUG
> 	LINKOPTIM : -O
> 
> 
> Building with 'nvcc'.
> /usr/local/cuda-7.5/bin/nvcc -c -DMX_COMPAT_32   --compiler-options=-D_GNU_SOURCE,-DMATLAB_MEX_FILE -I"/usr/local/MATLAB/R2016a/extern/include" -I"/usr/local/MATLAB/R2016a/simulink/include" -I"/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include/" -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=\"sm_50,compute_50\" $NVCC_FLAGS --compiler-options=-ansi,-fexceptions,-fPIC,-fno-omit-frame-pointer,-pthread -O -DNDEBUG /usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/src/mex/mexGPUExample.cu -o /tmp/mex_12118211229821_9269/mexGPUExample.o
> /usr/bin/g++ -pthread -Wl,--no-undefined  -shared -O -Wl,--version-script,"/usr/local/MATLAB/R2016a/extern/lib/glnxa64/mexFunction.map" /tmp/mex_12118211229821_9269/mexGPUExample.o   -Wl,-rpath-link,/usr/local/MATLAB/R2016a/bin/glnxa64 -L"/usr/local/MATLAB/R2016a/bin/glnxa64" -lmx -lmex -lmat -lm /usr/local/cuda-7.5/targets/x86_64-linux/lib/ -o mexGPUExample.mexa64


> Error using mex
> /usr/bin/ld: cannot find /usr/local/cuda-7.5/targets/x86_64-linux/lib/: File format not recognized
> collect2: error: ld returned 1 exit status
>

**Comment by AnderBiguri** [comment]
What did you do to force matlab to use it?

you just need to type     -mex setup    to make MATLAB use the right
compiler. Make sure you haven't deconfigured something.
Also, I'd try reinstalling CUDA 7.5, as you are getting some strange errors
 (File format not recognized).
It seems something to do with your local configuration.

I'd suggest you ask either in Stackoverflow or Mathworks help forums also,
as if the compilation of the MATLAB example does not work it definitely is
because something is not right in your local configuration, and you may
also get help there. I will still continue triying to look into this, but
again, unfortunately I do not have a Linux machine that I can play with now.

**Comment by AnderBiguri** [comment]
@nclprz  I am going to close the issue as it is not related to TIGRE but your local config. We can still talk in this thread, but it won't be an "open issue".

**Comment by AnderBiguri** [comment]
Hi @nclprz ,

did you managed to fix this?
Ander

**Comment by nclprz** [comment]
Hi @AnderBiguri ,

I actually gave up on Linux for the moment, and just managed to get everything to work on Windows.
I am still deciding whether to use ASTRA or TIGRE, and since I had problems with both of them on Linux (albeit different ones) I have decided to try them out on the OS I am the most comfortable with, and then fix the Linux installation of the one I ultimately decide to use.

Just as a quick question (I don't know if I should open another ticket): are the Demos that you provide with the toolbox tested to work "as provided"? Because I am having a few problems with them, some had easy fixes but others are just not working, so I am wondering if I correctly installed everything and just need to tweak the parameters or if I am still missing stuff (but on Windows, hence my doubt about opening a new ticket).

**Comment by AnderBiguri** [comment]
@nclprz Yes, the demos are supposed to work "as provided", but please, let me know what problems you have with them, some bug may have been accidentally introduced at some point. 

ASTRA vs TIGRE, the honest version:

- ASTRA has only 3 algorithms for 3DCT (CBCT or Parallel), FDK, CGLS and SIRT. TIGRE has more algorithms, as that is our objective.  You can technically create most of the algorithms on ASTRA, but they are not there.

- ASTRA has more tomography types. To do 2D tomography, ASTRA is straightforward. You can do in in TIGRE, but you need to slight "cheat". Results are good though.  However TIGRE has more flexibility in geometry types. E.g.  3D Helical scan is not currently available in ASTRA, but is straightforward in TIGRE

- ASTRA is faster than TIGRE, up to 5 times (in some very specific cases) around 2.5x in my tests. This is due to TIGRE having more flexibility and TIGRE algorithms being in MATLAB. This is specially noticeable the bigger the image gets. 

Thus, my recommendation: If you just want FDK, CGLS, SIRT algorithms, go for ASTRA, its just faster. 
However, in my experience, those are the algorithms that are "worst" (while still doing a good job). 
Else, I'd go with TIGRE. I coded TIGRE because ASTRA's flexibility and algorithms were just not good enough for me, so if I have done a little of a good job, then TIGRE should be better in that.

Ander

**Comment by nclprz** [comment]
@AnderBiguri Should I just type here the problems that I am having with the demos?

Regarding ASTRA vs TIGRE: I am fairly new to reconstruction problems. I am doing tomographies (CBCT) of bone samples and I was asked to look into iterative reconstruction to try to work with less projections, to reduce the scan times. Since I am so new to the programming problems of reconstruction, my initial idea was just to try and feed my data to the already existing toolboxes, to see what I can gather from the various algorithms, and then see where to go from there. Sadly, I had troubles even installing the toolboxes, haha! However, that is to say that I actually don't know yet which kind of algorithm I want to employ.

Niccolò

**Comment by AnderBiguri** [comment]
@nclprz  I then suggest you start with TIGRE, and if you end up deciding for CGLS or SIRT algorithms then you can move to ASTRA, but I suspect that if image quality is your objective, then TIGRE may help you better. Anyway, as it looks liek you are having personal problems with the demo (I run all of them in my PC and work fine) I suggest we take this conversation to email.

Please contact me further about this in a.biguri@bath.ac.uk or tigre.toolbox@gmail.com
