### ISSUE TITLE
Displaced detector(large-view) reconstruction problem

### ISSUE THREAD

**Issue by dyycy** [CERN/TIGRE#151]
I'm working on a project based on a medical CBCT scanner. The scanner provides a so-called _full view_ imaging function, where detector is 1/4 laterally displayed.
When I reconstructed projs by myself, the results looked kind of wired. After weeks on debugging, I realized that the demo _d14_Offsets.m_ was kind of missing leading. The toolkit is not off the shelf in using FDK to solve the _detector-offset_ problem. 

## Expected Behavior
For circular trajectory CBCT, when the detector is laterally displaced less than half of its lateral size, mathematically the central slice image exactly reconstructed, and images in other slices can be reconstructed accurately enough. This technique is also called, if my memory serves me well, _displayed detector imaging_ or _large-view imaging_.

The problem is reproducible by running the following code. It's still the d14_Offset.m. I changed the _geo.offDetector_ and added a FDK recon code block.

## Actual Behavior
A shining ring artifact shows, and streaks can be seen.
![Snipaste_2020-02-10_19-22-31](https://user-images.githubusercontent.com/7495679/74145912-df83ea80-4c3a-11ea-875b-a3528898ff31.png)
![Snipaste_2020-02-10_19-20-54](https://user-images.githubusercontent.com/7495679/74145931-ead71600-4c3a-11ea-905f-faad644d605e.png)

## Code to reproduce the problem (If applicable)

%% Define Geometry
geo=defaultGeometry('nVoxel',[128;128;128]);                     

% Offsets
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lets try simnple offset: The detector gets completelly displaced
geo.offOrigin = [0;0;0];                     % Offset of image from origin   (mm)              
geo.offDetector = [100; 0];                     % Offset of Detector            (mm)
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Auxiliary 
geo.accuracy=0.5;                           % Accuracy of FWD proj          (vx/sample)

%% Load data and generate projections 
% see previous demo for explanation
angles=linspace(0,2*pi,100);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');

%% lets see it
plotProj(projections,angles);

%% we will skip recosntruction of this tests because the image is outside the detector
res=FDK(projections,geo,angles);
plotImg(res,'Dim',3);

## Specifications 

  - MATLAB version: MATLAB 2018b
  - OS: Win 10
  - CUDA version: 10.1

## Some words:
I used to work this problem years ago. To cope with it, I think one more parameter is needed in FDK.m for workflow control, where projs should be pre-weighted before filtering. If anything, please drop a message or email yidu@bjcancer.org

**Comment by AnderBiguri** [comment]
Hi @dyycy ! Thanks for the thorough study. 
 So your proposed solution is to pre-weight the projections, right? 
I realized I have an open issue here in TIGRE about missing "Wang weights" for FDK offseted detectors, I assume you mean these?

 https://github.com/CERN/TIGRE/issues/101 

As TIGRE has was designed mostly with iterative algorithms in mind, most of the features were added on that mental framework. For iterative algorithms, these weights are not needed, so you can properly reconstruct detector-offset with TIGRE. But you are correct, FDK is missing an important feature there.  

I currently will be too busy to have a look at this for a few months, so I can not promise to add them anytime soon. However they don't seem too hard, if you decided to implement them I am more than willing to guide you with any questions about the current code and we can add them to TIGRE later. 

Best
Ander

**Comment by bnel1201** [comment]
@dyycy  I was having the same issue and added the preweighting you suggested following the [Ge Wang paper](https://aapm.onlinelibrary.wiley.com/doi/epdf/10.1118/1.1489043) mentioned in issue [# 101](https://github.com/CERN/TIGRE/issues/101)

I've copied your code and added the pre-weighting bit to the end.

%% Define Geometry
geo=defaultGeometry('nVoxel',[128;128;128]);

% Offsets
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Lets try simnple offset: The detector gets completelly displaced
geo.offOrigin = [0;0;0]; % Offset of image from origin (mm)
geo.offDetector = [100; 0]; % Offset of Detector (mm)

percent_offset = @(geo) geo.offDetector(1)/geo.sDetector(1) * 100;
fprintf("detector displacement: %0.2f percent \n", percent_offset(geo))
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Auxiliary
geo.accuracy=0.5; % Accuracy of FWD proj (vx/sample)

%% Load data and generate projections
% see previous demo for explanation
angles=linspace(0,2*pi,100);
head=headPhantom(geo.nVoxel);
projections=Ax(head,geo,angles,'interpolated');

%% lets see it
plotProj(projections,angles);

%% we will skip recosntruction of this tests because the image is outside the detector
res=FDK(projections,geo,angles);
plotImg([res, head],'Dim',3);

%% Add wang weights for offset detectors

overlap_in_mm = geo.sDetector(1)/2 - abs(geo.offDetector(1));
overlap_in_pix = round(overlap_in_mm / geo.dDetector(1));

t_in_mm = linspace(-overlap_in_mm, overlap_in_mm, 2 * overlap_in_pix);
R_in_mm = geo.DSO;
w = 0.5 * (sin((pi * atan(t_in_mm / R_in_mm)) / (2 * atan(overlap_in_mm / R_in_mm))) + 1);
w = repmat(w, [geo.nDetector(1), 1, size(projections, 3)]);

wang_weights = ones(size(projections));
wang_weights(:, 1:size(w, 2), :) = w;
if sign(geo.offDetector(1)) < 0
    wang_weights = fliplr(wang_weights);
end
wang_weights = 2 * wang_weights;
wprojections = projections .* wang_weights;
%% recon and view the result
wres=FDK(wprojections,geo,angles);
plotImg([wres, head],'Dim',3);

Here's the result I got on the left with the original head phantom on the right.
![wangweight](https://user-images.githubusercontent.com/21038704/88233363-2be94280-cc3d-11ea-849c-36d854f1e4e1.png)

Hope this helps!
