### ISSUE TITLE
Error using Ax_mex

### ISSUE THREAD

**Issue by JoaoWang** [CERN/TIGRE#166]
I've successfully installed TIGRE according to the installation guide, but when I run a demo, such as demo8, sometimes there will be a `Error using Ax_mex` . And if I rerun `complie. m` and `InitTIGRE. `, this error can be solved. 
![image](https://user-images.githubusercontent.com/64910341/82134467-dbafc780-982a-11ea-85f9-db0718196dbb.png)
This problem gives me a feeling that the effective time of each compilation is limited, so I have to recompile after a certain time interval, otherwise the C + + files cannot be called.
This constant problem is a troublesome matter. What can I do to solve it completely?

```

```

## Specifications 

  - MATLAB version: R2019a
  - OS: Win 10
  - CUDA version: V 9.2
  - C++ compiler: VS 2015

**Comment by AnderBiguri** [comment]
@JoaoWang This is *certainly* not caused by an "effective time". The reason it works when you recompile is because recompiling resets the device, thus gets the GPU out of failure mode. Any other way of resetting the GPU will cause the same effect. 

This, of course, does not explain why is this happening to you, which certainly should not be happening. Unfortunately CUDA is not being very helpful and the error we are getting is "unknown error". This can mean lots of things, but often it is linked to a bad CUDA installation. I suggest you try to reinstall CUDA (even better if you install 10.2) and then try to run some of the sampels before compiling and running TIGRE .

**Comment by JoaoWang** [comment]
@AnderBiguri 
Thanks for your advice, I will try it.

**Comment by JoaoWang** [comment]
Hi @AnderBiguri 
Thanks a lot for your suggestion, I tried to uninstall CUDA v9.2 and install CUDA v10.2. Now my problem has been solved and the program can run normally.

**Comment by AnderBiguri** [comment]
@JoaoWang Fantastic! do let me know if you have more problems with TIGRE.
