### ISSUE TITLE
FDK recon issue

### ISSUE THREAD

**Issue by rogerkuo1981** [CERN/TIGRE#167]
I am trying to use GPU based FDK to reconstruct the test CBCT data, but got wired result on the couple slices at the beginning and as well as the end. looks like from the first slice, there is a mask at the enter, and the diameter getting larger and larger slice by slice, after couple of slices, the issue just gone. then it come back on the last couple of slices, the 'mask' comes from outside, and diameter getting smaller and smaller. exactly the opposite way of the beginning.
I have checked the geometry parameter, and all of them looks correct. 
issue as picture shows below 
Any comments will be really really appreciated.

![recon-issue](https://user-images.githubusercontent.com/30967088/86472833-5fd5f400-bd72-11ea-89b0-6d586db2c917.JPG)

## Specifications 

  - MATLAB version: matlab 2015
  - OS: win10
  - CUDA version: 10.0

**Comment by AnderBiguri** [comment]
@rogerkuo1981 before I look this further: try to do the same recon with the angles negated (`angles=-angles`)

**Comment by rogerkuo1981** [comment]
> @rogerkuo1981 before I look this further: try to do the same recon with the angles negated (`angles=-angles`)

Hi Dear AnderBiguri, thanks for you prompt reply!!!! i tried to use negated angles, images flipped around, but the mask still there.

**Comment by AnderBiguri** [comment]
@rogerkuo1981 I suggested the negative mostly because your image does not look right as you show it. You are looking at that mask, which may just be a standard cone artifact (check the images in the coronal axis, z), but however your images don't look like the right shape. The body looks like a cardioid with a very round shape. The bone structure also does not seem completely in focus, so all hints for slight mismatches in geometry. Often this happens due to having the angles in a different format/direction than what TIGRE expects.

**Comment by rogerkuo1981** [comment]
@AnderBiguri Yes, you are right, when i look at the coronal images, it looks like the cone artifact. I will go check the geometry again. Thank you very much for your help!
![coronal](https://user-images.githubusercontent.com/30967088/86480828-5bfd9e00-bd81-11ea-9d4b-bd47e86c7d01.JPG)

**Comment by AnderBiguri** [comment]
@rogerkuo1981  I am closing this issue as resolved, do let me know if you have more problems.
