### ISSUE TITLE
DBT SART reconstruction on cropped region in projections

### ISSUE THREAD

**Issue by roshtha** [CERN/TIGRE#176]
Hello,

I use TIGRE SART for DBT image reconstruction. 
To reduce reconstruction time I have cropped region of interest on input projection data before giving to SART algorithm. But the final image output  lost background information outside cropped regions since the width of cropped projection is less than the image to be reconstructed. 
Is it a good approach to do reconstruction on a cropped region ? 
What modifications we need to do in TIGRE to avoid the cropping effects in final output image?

![Untitled](https://user-images.githubusercontent.com/5310634/89860584-6e10fe80-dbc1-11ea-8cb9-3cf3e6c58525.png)

## Specifications 

MATLAB version: Matlab 2015b
OS: Windows 10, 64 bit
CUDA version: 10.2

**Comment by AnderBiguri** [comment]
@roshtha ah, yes and no! Cropping is OK, but you have not done cropping.

For the FDK algorithm, cropping and zeroing is the same, because the first thing the algorithm does is a high pass filter. But in any other algorithms, zero is as valid for a pixel value as any other pixel! If you zero a part of thr image you are not telling the algorithm to ignore it, you are telling it that there were no x rays there and that it must enforce that. This is kot what you want. 

To crop in iterative algorithms you need to properly cut the projections, making them smaller. You will also need to change the geometry to describe the new, smaller detector, by changing geo.nDetector and geo.sDetector

**Comment by roshtha** [comment]
Thanks @AnderBiguri.
