### ISSUE TITLE
Reconstruction of C-arm CBCT projections

### ISSUE THREAD

**Issue by roshtha** [CERN/TIGRE#202]
Hello,

I wanted to apply TIGRE for the reconstruction of C-arm CBCT projections. Is there a demonstration script available to start with C-arm CBCT reconstruction? Or can I use d19_DBTexample.m (without updating geo with a call to staticDetectorGeo) for this reconstruction?

Thanks.

**Comment by AnderBiguri** [comment]
Hi @roshtha ,

Indeed I think I need to add a proper working example for C-arm CBCT. 
What you really need is the stuff in d018: setting up arbitrary axis of rotation. 
The way you can crate arbitrary paths is by rotating the detector using 3 angles, euler ZYZ angles in particular, around the origin (generally, the center of the image). This allows you to basically, for each projection, set the detector anywhere around the image. 

I understand that its not 1to1 from a C-arm angles to CBCT, you will likely need to convert whichever paths you have to positions described by these euler ZYZ angles. 

Hope this helps, otherwise please feel free to ask more or send me an email. 

Ander

**Comment by AnderBiguri** [comment]
Hi @roshtha how is this going?

I have a collaborator who worked on this that would be happy to have a discussion via email if you are having trouble with it. 
Let me know, so we can make sure you can do the stuff you want and I can close this issue.

**Comment by roshtha** [comment]
Hi @AnderBiguri, 

Thanks for offering help. I am very new to C arm CT technology and I tried OS_SART with d018 demo script. But could not get expected results and now verifying the geometry part. I will send the code I tried along with geometry and raw data through mail. It would be very helpful if you can guide on this. 

Thanks.

**Comment by lkccu** [comment]
> Hi @AnderBiguri,
> 
> Thanks for offering help. I am very new to C arm CT technology and I tried OS_SART with d018 demo script. But could not get expected results and now verifying the geometry part. I will send the code I tried along with geometry and raw data through mail. It would be very helpful if you can guide on this.
> 
> Thanks.

Hi, have you figured that out? I have a same trouble now.
