### ISSUE TITLE
POCS algorithms behave differently on MATLAB and python

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#223]
This has been reported. Investigate.

**Comment by yliu88au** [comment]
@AnderBiguri I can see three issues here:
(1) FDK algorithm returns two different results from MATLAB and Python versions;
(2) 2D case specific: Remember in MATLAB version of minTV and AwminTV, we need to duplicate and pad 2D [m,n] array as [m,n,2] before we passing it to GPU to process. And then trim the returned result back to [m,n] array. In Python, 2D case will have [1,m,n] array, which is passed to GPU directly for processing. Question is, should we also duplicate and pad to [2,m,n] array in _minTV.pyx and _AwminTV, and then trim back?
(3) Since the GPU code for both version are same POCS_TV.cu and POCS_TV2.cu, my question is, will the returned result from GPU consistent when we feed it with [2,m,n] array or [m,n,2] array?

**Comment by yliu88au** [comment]
Example code for 2D and 2D.

[example.zip](https://github.com/CERN/TIGRE/files/5713358/example.zip)

**Comment by yliu88au** [comment]
@AnderBiguri I think I have fixed issues (2) and (3) in PR 228. Issue (1) still remains.

**Comment by AnderBiguri** [comment]
Thanks for this comments and the PR!

As tyou say in (3), we might need to change a couple of things in the cuda source. It would be interesting to test with m==n first and compare both python and MATLAB to see if that is the same, and then change it. I suspect as you say (and I commented in the PR) that this has a negative influence. 

I opened #229 for FDK
