### ISSUE TITLE
SART with FDK initialized image - Artefacts in reconstructed image

### ISSUE THREAD

**Issue by roshtha** [CERN/TIGRE#240]
Hai,

I applied SART algorithm with FDK output as initialization image for DBT reconstruction from raw projection data (`followed d19_DBTexample.m`). Then I could see stripe like artifacts in the reconstructed images. For some slices, this is prominent across the whole image.

![Artifacts1](https://user-images.githubusercontent.com/5310634/104409419-3cdf9480-558c-11eb-8379-807da5aea3e7.png)

Also while zooming images, I could see some noise patterns in the images. 
![Artifacts2](https://user-images.githubusercontent.com/5310634/104409302-fab65300-558b-11eb-82e2-2b7dffb3b27c.png)
Could you please provide hints on how to get rid of these artifacts? 
What could be the possible reasons for these artifacts? 

Thanks.

**Comment by AnderBiguri** [comment]
Hi @roshtha 

If you just do FDK reconstruction, are those patterns also there? I suspect the answer will be yes.  If that is the case: My hunch is that this is caused by the FDK image. 

When you initialize your image to all zero (i.e. normal SART), the image after reconstruction is not 100% the truth, there will be always some part with errors. The same happens when you initialize with FDK. 

The issue is that this errors are caused by the algorithm not having fully converged, and due to the way these algorithms behave, that means that the pixel values did not move 100% to their real values, from their original position. When you initialize the image with all zeroes (i.e. standard recon params), this tends to look like a blur (try 1 iteration of SIRT), but when you initialize your image with some other image, then undercoverged images tend to look like that initialization image.  The same will happen if you initialize the volume with a photo of a cat, for example. Its possible that unless you iterate a lot, you will still see remnants of that image. If your FDK image is very good (i.e. it looks like the result), then you are making a favor to SART, because all pixels are much closer to the real solution, thus SART needs to do less effort. However if your initial image makes a pixel value be much further from the solution than if it was of value zero (e.g. by a stripe artifact in FDK), then you are doing a disservice, you make SART work much harder for its solution than before, meaning you may get residuals of artifacts in the image.  

I suspect that this is your what you see. The images still have the artifacts that FDK generates. Solution? There is none clearly. Maybe iterating much much longer will remove them. Or preprocess the FDK image (blurr it, remove artifacts, etc) and then input it as initial image.

**Comment by roshtha** [comment]
Hai @AnderBiguri,

Thanks for your detailed explanation. I proceed by applying some preprocessing to FDK images before inputting to SART.
