### ISSUE TITLE
seemingly inconsistent integrals of projections from simple example data?

### ISSUE THREAD

**Issue by currymj** [CERN/TIGRE#38]
Below is a script that runs an experiment performing projection on a volume with only a single voxel initialized. It runs for quite a while; you may want to limit the number of angles or the number of voxel sizes for testing purposes. The output is in the `result` variable. 

The integrated projections of this single voxel over the entire projection plane are not consistent for different voxel dimensions and different projection angles. Do you know why this might be the case? Is this due to approximation error in the projection routine, a bug, PEBKAC, or something else?

A scientist I am working with says "The consistency of these integral values defines the quality of the entire reconstruction process."

```MATLAB
smallgeo.DSD = 1200;
smallgeo.DSO = 1000;
smallgeo.nDetector=[512;512];
smallgeo.sDetector=[128;128];
smallgeo.dDetector=[.25;.25];
smallgeo.offOrigin =[0;0;0];                     % Offset of image from origin   (mm)              
smallgeo.offDetector=[0; 0];                     % Offset of Detector            (mm)

result = [];
for ii=2:64
        dim = ii;
        smallExample = single(zeros([dim dim dim]));
        nearCenter = floor(dim / 2);
        smallExample(nearCenter, nearCenter, nearCenter) = 1;

        smallgeo.nVoxel = [dim;dim;dim];
        smallgeo.sVoxel = [dim;dim;dim];
        smallgeo.dVoxel = [1;1;1];

        smallExample2 = single(zeros([dim dim dim]));
        smallExample2(nearCenter+1, nearCenter+1, nearCenter+1) = 1;

    for angle=linspace(0, 2*pi, 100)
        smallProjection = Ax(smallExample, smallgeo, [angle], 'interpolated');
        sum(smallProjection(:));
        proj2 = Ax(smallExample2, smallgeo, [angle], 'interpolated');
        sum(proj2(:));
        result = cat(1, result, [dim angle sum(smallProjection(:)) sum(proj2(:))]);
    end
end
```

**Comment by AnderBiguri** [comment]
Hi!
I will have a further look at this tomorrow but it looks that this comes
from the use of grid interpolation projection. Surely at different sizes
the interpolation kernel runs further (in mm). Try the same code but withe
the other projection method. There is a demo about this effect, the
projection types demo.
Ander

**Comment by currymj** [comment]
Thanks for pointing me at that demo!. Increasing the accuracy seems to fix the problem. The only problem we observe now involves volumes with odd numbers of voxels, but this seems like an issue that shouldn't cause any problems for us.

**Comment by AnderBiguri** [comment]
Hi @currymj , 
I am glad that helped. 
While decreasing the accuracy value (increasing accuracy) will help make the results more similar, if you want 100% robustness on that, use `Ax(smallExample, smallgeo, [angle], 'ray-voxel');` . This uses exact radiological path to compute the image path, computing the intersections between voxels and lines. 

This method (Siddons/Jacobs method, i.e. ray-voxel) is supposed to have the hihgest accuracy when reconstructing, according to the paper ["A comparative study of popular interpolation and integration methods for use in computed tomography"](http://ieeexplore.ieee.org/document/1625152/?reload=true), followed by the grid-interpolated method very closely.  When working in big resolution (small voxel size) the difference between reconstructions using them generally of the order of 0.01% of the image value, as a maximum. 

So which one should you use? It depends. TIGRE defaults to use the grid-interpolated because generally the images are high resolution and pixel values smooth, i.e. there are generally no high values in single pixels0. Not that it makes much difference.  The only notable difference happens when working with low res images and high res detectors. However, one can argue that the interpolated method, while inconsistent, its more according to real life. The case where the real image is a single cube aligned with the voxel representation is almost impossible. Thus, a single white voxel  may better be a "round" white object, thus interpolating its values around is more representative of any real image. Using the Siddon's method would essentially create aliasing. 

I hope this explanation is clear!

Additionally I need to have a look at odd sized images.  I reckon I have looked at that in the past, but as the case almost never happens in my day to day usage, I'd need to look better, as there may be a half-voxel offset somewhere (I don't think so). Please, do report any error you may encounter there!

Best
Ander
