### ISSUE TITLE
mex_CUDA_glnxa64.xml library issues

### ISSUE THREAD

**Issue by rffowler** [CERN/TIGRE#4]
mex_CUDA_glnxa64.xml requires libcudart to link. It assumes this is installed under MATLABROOT. By default (on R2014a) this is not the case and it can be found under e.g. /usr/local/cuda-7.5/targets/x86_64-linux/lib.
It also has a reference to the mwgpu library "-lmwgpu" which is not in the windows version; if this library is not installed the compiliation will fail. Removing the reference seems to fix the problem.
Apart from that it builds OK on CentOS 6.8.

**Comment by AnderBiguri** [comment]
Hi @rffowler , I have no access to a linux system at the moment so I can not try to fix/test it myself. 
Do you mind telling me exactly what lines need to be changed by what other, please? I will change the file and commit if you do so. Thanks for the raising the issue!

**Comment by rffowler** [comment]
Hi Ander,
I see you have patched the git xml file in question. While I agree with removing the reference to “–lwmgpu”, I don’t believe the change to the CUDA path will work. However I am not sure what is the best way to fix it in general as it depends on the version of CUDA and where it is installed.
The diffs of my xml and the original are:

34c34
<           NVCCFLAGS="-gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=&#92;&quot;sm_30,compute_30&#92;&quot; $NVCC_FLAGS"
---
>           NVCCFLAGS="-gencode=arch=compute_13,code=sm_13 -gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=&#92;&quot;sm_30,compute_30&#92;&quot; $NVCC_FLAGS"
44c44
<           LINKLIBS="-Wl,-rpath-link,$MATLABROOT/bin/$ARCH -L&quot;$MATLABROOT/bin/$ARCH&quot; -lmx -lmex -lmat -lm -L/usr/local/cuda-7.5/targets/x86_64-linux/lib -lcudart"
---
>           LINKLIBS="-Wl,-rpath-link,$MATLABROOT/bin/$ARCH -L&quot;$MATLABROOT/bin/$ARCH&quot; -lmx -lmex -lmat -lm -lmwgpu $MATLABROOT/bin/$ARCH/libcudart.so.7.5"

The compiler I used (7.5) didn’t support version “13” so I had to delete that. For the CUDA libs I used an explicit “-L<path_to_cuda> -lcudart”. Obviously this will vary if the user installs cuda somewhere else or uses a different version of CUDA. Maybe just mention that this line may need to be altered?
Hope that helps. Thanks for the fast response.
Regards,
Ron Fowler
STFC.

**Comment by AnderBiguri** [comment]
@rffowler Thanks for the insight on that. 
Yes, the problem is that the toolbox is untested in linux systems and they generally have more specific paths and properties, but I now realise that there may be a bit more work here to do, as several interesting flags (such as compute_50 and other newer versions) are missing from the linux xml file.

I will try to install a linux partition in my PC and  test these things. Thank you for letting us know about this, and do not hesitate to contact us with further issues/questions.
Best
Ander

**Comment by rffowler** [comment]
Hi Ander,
I just had a thought, the reason I don’t have the cudart library in my matlab root directory is probably because I don’t have a license for the “distcomp” toolbox or whatever it is that matlab sell for parallel computing. Hopefully the code will work without that toolbox as long as I am not in “developer” mode. It seems to have compiled anyway using the script you provided which avoids “mexcuda” commands. Users who have this toolbox may not have problems with the previous settings of the cudrt location.
Regards,
Ron

**Comment by AnderBiguri** [comment]
Hi Ron, @rffowler 
Yes that is definitely the case, but in theory the toolbox does not need the distributed computing toolbox to run, as it does not use any of the functions/utilities on it.  I rather leave it as it is (pointing at user's CUDA), as the users will need it installed to compile. The reason that was as it is in the first place is because the xml is provided by MATLAB, and I didn't modify the linux one. 

In the last commit I added some extra compiler flags for newer GPU architectures. I suggest adding these to your local version and recompiling it, as in the past I increased the speed of the CUDA kernels by about 30% just by updating these flags (can't remember from which version to which other) . You may or may not get this speedup but its worth a try. 

Best,
Ander
