### ISSUE TITLE
TIGRE only compiles with Visual Studio on Windows

### ISSUE THREAD

**Issue by AnderBiguri** [CERN/TIGRE#42]
This is a problem with CUDA, that does not seem to accept MinGW and SDK7.1 on Widows. This has been confirmed by Mathworks:

> The supported compilers for CUDA on Windows are determined by NVIDIA and the CUDA version. On Linux we have a lot of freedom and just need a compiler which is part of the gcc toolchain. However in Windows we are limited to Visual Studio. We checked out NVIDIA's forums to see if there was much 
> traction going on there with support for things like MinGW etc. What we found there was users with similar pain about trying to get CUDA code 
> compiled under Windows outside of the Visual Studio toolchain but no solutions as of now.
> 
> So, the only supported compiler for CUDA on Windows is Visual Studio with nvcc as of now.

If someone is able to find a workaround, please contact us!

Meanwhile, I have some compiled files (`.mex64`). They may work in other Winx64 computers, but there is no way to tell 100% sure. If you work in Windows, contact me (via author email or TIGRE email) and I will send you the compiled files.

**Comment by AnderBiguri** [comment]
While most MATLAB "supported compilers" seem to suggest that you need Microsoft Visual Studio 20XX Professional, It seems that the community (free) edition does compile proper TIGRE mex files.

Tested in:

- MATLAB R2016a , Visual Studio 2013 Community 




(Please let me know if you tested it and I will add more)

**Comment by S-Fink** [comment]
Hi @AnderBiguri,
How do I get Matlab (MATLAB R2016a) to recognize "Visual Studio 2017 Community" (or any other compiler that is not listed as supported) as a "supported compiler"?
Thx,
Simone

**Comment by AnderBiguri** [comment]
Hi @S-Fink, 
Technically you can not use an unsupported compiler. However some of the community versions **of the supported VS versions** may work.  However it may not work. 
I suggest you try one of the free versions of the supported ones. 
Best 
Ander

**Comment by mike3679** [comment]
Hi @AnderBiguri,
I seem to be having a similar issue...have MinGW and SDK 7.1 compliers but getting error of no supported CUDA compiler when I go to compile (selecting SDK 7.1 in mex -setup).  I also have Visual Studio 10.0 (32 bit) and when I run mex -v -setup it shows that it finds that under the SDK compiler.  In your above posts you say that it only compiles with Visual Studio...is this the Visual C++ 20xx that the mex -v -setup lists?  If so do I need to get a stand alone license for visual studio that is the 64 bit flavor?  thanks and sorry about my lack of clarity as I am a relatively novice at software building.

**Comment by AnderBiguri** [comment]
@mike3679 Yes, MinGW is not compatible, that is 100% certain.

In order to be able to compile the MATLAB version in Widows, you need a Visual Studio that is **both** compatible with the MATLAB version you are using **and** the CUDA version you are downloading.  This changes in each version of CUDA and MATLAB (ughhhh) so you need to carefully check both. Then indeed once oyu have that specific version of Visual Studio it should just setup properly and compile.

**Comment by mike3679** [comment]
CLASSIFICATION: UNCLASSIFIED

thanks

-----Original Message-----

**Comment by mike3679** [comment]
CLASSIFICATION: UNCLASSIFIED

Hi, got it up and running as you  mentioned using Visual Studio 15/Matlab 2017a/Cuda 8.  One thing I did need to change was in the compile file.  Needed to change from "mex" to "mexcuda" to get the nvcc to compile it.

Cheers.

mike

-----Original Message-----

**Comment by AnderBiguri** [comment]
@mike3679 Yes, this should be done for new versions of MATLAB apparently. I should try to improve the compiler file....

Glad it worked, do not hesitate to email any question you might have!

**Comment by mike3679** [comment]
CLASSIFICATION: UNCLASSIFIED

Hi Ander,
I am interested in your code for the iterative capabilities.  I am performing few-flash NDT radiography.  Now that I have gone through the code, I am not sure it will be viable for me because I have a non-symmetric source/detector sampling of the system (still cone beam).  Is there any way to input sources that utilize different source to detector distances?  I realize that you can translate the detector and tilt/rotate it, but I am not sure how to set up an input for my case.  For example, in real space, when my object is centered at the origin, I have the following 5 source detector pairs:
			x-position (m) 	y-position (m)	z-position (m)			Distance from Origin (m)	Source/Detector Separation (M)
							
Source_300_1		0.952295877	-0.014345129	0.296006053			0.997342872	
Detector_300_1	-0.946263723	-0.010142162	-0.319478106			0.998791348			1.99613422
							
Source_300_2		-0.978364446	-0.011915856	0.251201682			1.010168928	
Detector_300_2	0.941421624	-0.014202481	-0.278977313			0.981990186			1.992159114
							
Source_300_3		-0.570893767	-0.821886102	-0.634440506			1.184876032	
Detector_300_3	0.554975234	0.778788239	0.571178891			1.113891358			2.298767391
							
Source_300_4		0.50058212	-0.611046889	1.024679809			1.293804263	
Detector_300_4	-0.534606062	0.574019363	-1.080328695			1.335070021			2.628874283
							
Source_300_5		-0.810875709	0.895273276	0.452186457			1.289769842	
Detector_300_5	0.783283106	-0.937918352	-0.509386691			1.323895034			2.613664876

I have attached an excel spreadsheet that summarizes the data in this email incase the formatting is lost (all distances in meters). Thanks much.

mike

-----Original Message-----

**Comment by AnderBiguri** [comment]
Hi Mike,
 Consider sending me an email, instead of adding the infromation in an
unrelated Issue on Github.

Best
Ander

**Comment by mike3679** [comment]
CLASSIFICATION: UNCLASSIFIED

Sure, what is your email address?
thanks

-----Original Message-----

**Comment by AnderBiguri** [comment]
Use ander.biguri@gmail.com @mike3679

**Comment by ehdsilva** [comment]
Hi, I think I am having similar problem but since I am not experienced in software building as well, I am not sure on how to fix it. I am running TIGRE on matlab 2017a, visual studio 2015 and cuda 9.1. I tried to do a reconstruction and got a message saying "Invalid MEX-file C:\TIGRE\Mex_files\win64\Atb_mex.mexw64': Missing dependent
shared libraries:
'cudart64_92.dll' required by 'C:\TIGRE\Mex_files\win64\Atb_mex.mexw64'." I also tried with cuda 8.0 and 9.0, and I always get the same message. Would it work only with cuda 9.2? If I try to run compile.m it also says there is no supported library and that it cannot find cudart.lib

thanks

**Comment by AnderBiguri** [comment]
hi @ehdsilva, If you do not have CUDA 9.2 (hint: the latest the CUDA, the fastest the code) you will sure need to compile it yourself. Even with CUDA 9.2, you may need to compile it yourself, as its not 100% sure that it will work, unfortunately. 

To run Compile.m, check the mex_win64.xml first. Inside there there is a couple of lines that point to the current installed fdoler for CUDA. Replace those with your current installation path. Hopefully that shoudl work. If not, please let me know so we can go through this in more detail.

**Comment by AnderBiguri** [comment]
@ehdsilva  there seems to be a piece of code in the compile.m file that I left that only looks for CUDA 9.1. 

Change the library paths to your CUDA version here:

https://github.com/CERN/TIGRE/blob/master/MATLAB/Compile.m#L110

**Comment by AnderBiguri** [comment]
I am clossin this issue as it is not related to TIGRE, but to CUDA
