### ISSUE TITLE
cbct image reconstruction for low number of projection

### ISSUE THREAD

**Issue by shaghayegh1376** [CERN/TIGRE#424]
The question I had is that among the iterative algorithms that reviewed in this toolbox, as well as TV-based algorithms, which one works better for image reconstruction with low number of projection? asdpocs?

**Comment by AnderBiguri** [comment]
Hi!
There is no good answer, but yes, I would start with asd-pocs or os-asd-pocs. They are fairly good, but their parameters are quite hard to find. All of the TV ones are good, but I tend to recommend starting with those because they are more used in the literature and you can compare the results visually better with what is expected. 

But in general there is no "better", it all depends on what the image is going to  be used for.
