### ISSUE TITLE
How to do a FDK reconstruction without circle streaks?

### ISSUE THREAD

**Issue by Lxy98Code** [CERN/TIGRE#481]
Hi! 
We're currently engaged in the process of FDK reconstructing a 3D object. However, we're encountering difficulties in eliminating the circular streaks around in the resulting reconstruction. Despite some efforts, we haven't yet identified an effective solution. If there are adjustable parameters that could potentially address this issue, we kindly request your guidance on how to proceed. Alternatively, is it possible to support FDK reconstruction without circle streaks?

Hope it make sense,
Thanks!

**Comment by AnderBiguri** [comment]
Hi @Lxy98Code, can you show an image of the artifacts, so I can know what you mean?

The main reason TIGRE exists, is because FDK is a fairly bad algorithm, and unless working with perfect acquisition data, it tends to produce severe artifacts. This is why TIGRE has more that 10 algorithms, that should perform better. For example, you could try OS-SART. 

That said, sometimes the cause of the artifacts can be some geometric mistake, so if you show me how they look like, I may be able to infer where they come from.
