### ISSUE TITLE
FDK behaviour strangely

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#49]
Hello, @AnderBiguri 
when I using FDK in TIGRE to reconstruct a image, I find the cylinder can't be reconstruct correctly when the cylinder isn't positioned in the rotation origin.
![ld63_0 23j5p7qrd_6697b](https://cloud.githubusercontent.com/assets/17542372/26751812/26370c40-4875-11e7-845c-9e395049f664.png)
for example, this is the central slice reconstruct by tigre and:
![d86q _ d_sfnyk zgr3f_a](https://cloud.githubusercontent.com/assets/17542372/26751828/5011b2fe-4875-11e7-8e4a-81f437362b44.png)
this is reconstruction by another tool just with the same parameters, please notice the two small circle inside.
could you please tell me where is the problem? Thank you!

**Comment by AnderBiguri** [comment]
Have you set the geometry correctly? You say that it's not centred, is that
an offset in the image, the detector or you have a different centre of
rotation?
Can you show a small example to reproduces the same effect?
Ander

**Comment by ilanzhang** [comment]
![mzjt8w p 6 p5 wun6fr](https://cloud.githubusercontent.com/assets/17542372/26751995/8f1a91f2-4878-11e7-94b7-e83384fb8926.png)

just as the above phantom shows, the rotation axis is along the center of the small blue cylinder. and this blue cylinder could be reconstruct correctly, but those isn't symmetrical along the rotation axis, for example, the two small green cylinders, couldn't be correctly reconstruct.
is it the offset in the geometry?


![b5t5k1io1iu 9x 8w _m7x8](https://cloud.githubusercontent.com/assets/17542372/26752031/466ef064-4879-11e7-81ea-fc5966102bdb.png)


the above reconstruction image should all be slices of cylinders, but you can see, nearer to the rotation axis, more accurate it is.

**Comment by AnderBiguri** [comment]
Hi,
Sorry I get a bit confused. What small blue cylinder? What small two green
cylinders?
Another possible cause is the sign of the angles, but may be hiving them in
the opposite direction.
Ander



On 3 Jun 2017 09:25, "ilanzhang" <notifications@github.com> wrote:

[image: mzjt8w p 6 p5 wun6fr]
<https://cloud.githubusercontent.com/assets/17542372/26751995/8f1a91f2-4878-11e7-94b7-e83384fb8926.png>

just as the above phantom shows, the rotation axis is along the center of
the small blue cylinder. and this blue cylinder could be reconstruct
correctly, but those isn't symmetrical along the rotation axis, for
example, the two small green cylinders, couldn't be correctly reconstruct.
is it the offset in the geometry?

[image: b5t5k1io1iu 9x 8w _m7x8]
<https://cloud.githubusercontent.com/assets/17542372/26752031/466ef064-4879-11e7-81ea-fc5966102bdb.png>

the above reconstruction image should all be slices of cylinders, but you
can see, nearer to the rotation axis, more accurate it is.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CERN/TIGRE/issues/49#issuecomment-305960522>, or mute
the thread

**Comment by ilanzhang** [comment]
sorry, I first use another picture and now I have changed.
you have find out the reason before I explain it clearly, it's the direction of rotation.
thank you very much!

**Comment by AnderBiguri** [comment]
No worries!
