### ISSUE TITLE
Won't Compile - OS X 10.12 // MATLAB R2017a // Xcode 8.3.3 // CUDA 8

### ISSUE THREAD

**Issue by danielbriggs** [CERN/TIGRE#57]
Hi,
I can't get Tigre to compile under OS X 10.12, with MATLAB R2017a, Xcode 8.3.3 and CUDA 8
Any ideas / pointers?

I get the following compilation error:

> Compiling TIGRE source...
> This may take a couple of minutes....
> compiling for mac 64
> Building with 'nvcc'.
> Error using mex
> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use
> -Wno-deprecated-gpu-targets to suppress warning).
> nvcc fatal   : The version ('80100') of the host compiler ('Apple clang') is not supported

**Comment by AnderBiguri** [comment]
Open the xml file for Mac and find a very long line with a long list of
compilation flags. Removing the ones matlab (cuda actually) complains about
should so the job, I hope.

On 1 Aug 2017 23:48, "Daniel Briggs" <notifications@github.com> wrote:

Hi,
I can't get Tigre to compile under OS X 10.12, with MATLAB R2017a, Xcode
8.3.3 and CUDA 8
Any ideas / pointers?

I get the following compilation error:

Compiling TIGRE source...
This may take a couple of minutes....
compiling for mac 64
Building with 'nvcc'.
Error using mex
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are
deprecated, and may be removed in a future release (Use
-Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal : The version ('80100') of the host compiler ('Apple clang') is
not supported

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CERN/TIGRE/issues/57>, or mute the thread

**Comment by danielbriggs** [comment]
Thanks - that removed the warnings, but was still failing.
I rolled back Xcode from the current version (8.3.3) to 8.2 and this solved the issue.
Tigre now compiles. Thanks! Issue closed.
