### ISSUE TITLE
When I used the FDK reconstruction algorithm from the TIGRE library to obtain a CT reconstruction image, and then used the Ax function to simulate the CT projection, I found that the simulated projection did not match the original projection, and I don't know where the problem lies.

### ISSUE THREAD

**Issue by dialyCT** [CERN/TIGRE#604]
## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB/python version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
Ah, welcome to the world of inverse problems! The reason something like TIGRE exists with so many algorithms is because none of the algorithms will produce a perfect reconstruction (otherwise we would use that one every time!)

CT is an inverse problem, thus due to the ill-possedness of the problem, an exact reconstruction will never be possible. This is even more if you have real data, with noise and non-linear effects. 

If you could get a perfect reconstruction, my research field would not exist!

**Comment by dialyCT** [comment]
D家唔得闲等一下再找你
