### ISSUE TITLE
error occurs when install tigre-1.2

### ISSUE THREAD

**Issue by ilanzhang** [CERN/TIGRE#63]
Hi:
  when i install the version of 1.2, some errors show and i do not know how to resolve it? this is the error:
 
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
Ax.cpp
C:/Program Files/MATLAB/R2016a/extern/include\tmwtypes.h(788): fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory

 thank you!

**Comment by AnderBiguri** [comment]
Open the xml file, and somewhere in the middle of there is a long line with
those exact flags. Delete the flags that refer to numbers smaller than 30.


On 25 Oct 2017 08:09, "ilanzhang" <notifications@github.com> wrote:

Hi:
when i install the version of 1.2, some errors show and i do not know how
to resolve it? this is the error:

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are
deprecated, and may be removed in a future release (Use
-Wno-deprecated-gpu-targets to suppress warning).
Ax.cpp
C:/Program Files/MATLAB/R2016a/extern/include\tmwtypes.h(788): fatal error
C1083: 无法打开包括文件: “stddef.h”: No such file or directory

thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CERN/TIGRE/issues/63>, or mute the thread

**Comment by ilanzhang** [comment]
IS this line?

COMPFLAGS="-gencode=arch=compute_20,code=sm_20 -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=&#92;&quot;sm_50,compute_50&#92;&quot; -gencode arch=compute_52,code=sm_52 --ptxas-options=-v --compiler-options=/c,/GR,/W3,/EHs,/nologo,/MD"

and I should delete "-gencode=arch=compute_20," and the line become the :

COMPFLAGS="-gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=&#92;&quot;sm_50,compute_50&#92;&quot; -gencode arch=compute_52,code=sm_52 --ptxas-options=-v --compiler-options=/c,/GR,/W3,/EHs,/nologo,/MD"

**Comment by AnderBiguri** [comment]
Exactly that. There are 3 xml files, pick up the one of your OS. you can
ignore the rest

**Comment by ilanzhang** [comment]
I have tried but the error still shows up, my  computer is win10, and i delete in win64.xml

**Comment by ilanzhang** [comment]
this time the error becomes :
Ax.cpp
C:/Program Files/MATLAB/R2016a/extern/include\tmwtypes.h(788): fatal error C1083: 无法打开包括文件: “stddef.h”: No such file or directory
and there is no:
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

**Comment by AnderBiguri** [comment]
Hum...... Try mexcuda instead of mex, in the lines if compile.m.

Is this happenings online with the last version of tigre? The compile.m and
mex files should be unchanged from previous versions unless I accidentally
inserted a bug.

If you have an older version of tigre compiled, use the same code as then
to compile the new one.

On 25 Oct 2017 08:28, "ilanzhang" <notifications@github.com> wrote:

this time the error becomes :

Ax.cpp
C:/Program Files/MATLAB/R2016a/extern/include\tmwtypes.h(788): fatal error
C1083: 无法打开包括文件: “stddef.h”: No such file or directory
and there is no:

nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are
deprecated, and may be removed in a future release (Use
-Wno-deprecated-gpu-targets to suppress warning).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/CERN/TIGRE/issues/63#issuecomment-339240044>, or mute
the thread

**Comment by ilanzhang** [comment]
i use a different computer to run the new version of tigre, and the versions of vs and cuda are newer too, I dont know how to modify the xml file so that i use a same version of cuda to compile the tigre...and try mexcuda instead of mex, in the lines if compile.m, change the mex to mexcuda in the compile.m?

**Comment by AnderBiguri** [comment]
Yes try that inside compile.m

**Comment by ilanzhang** [comment]
if changed with mexcuda, just connot find the supported compiler or SDK in my computer

**Comment by AnderBiguri** [comment]
Can you tell me the exact os, matlab version and compiler version, both
cuda and visual studio?

**Comment by ilanzhang** [comment]
win10, matlab r2016a, cuda 8.0, vs2015 ult,
Thanks for helping me!

**Comment by AnderBiguri** [comment]
Hum everything seems to be OK. Is the cuda installation a custom one? Does
matlab known where cuda is? You need to do "getenv('NVCC_PATH')" I think.

 I'm not in my pc today so I won't be able to test it unfortunately.

**Comment by ilanzhang** [comment]
getenv('NVCC_PATH') get nothing but getenv('CUDA_PATH') get the real CUDA path, does it matters?

**Comment by AnderBiguri** [comment]
Have you got any further with this? I genuinely have no idea what can it be. It is strange, because the first error you mention is an error that I have only seen in Linux systems, however you get it in Windows.

**Comment by AnderBiguri** [comment]
Wait, your error is actually stddef.h! This has nothing to do with MATLAB or CUDA, this is an stardard C library. Do the xml file link to the correct installation of visual studio?

**Comment by ilanzhang** [comment]
Thanks for replying! I just replaced the compile.m and xml file with the version i've used and it just compiled successfully. :）

**Comment by AnderBiguri** [comment]
Glad it helped!
