### ISSUE TITLE
Really Odd demo output

### ISSUE THREAD

**Issue by dyycy** [CERN/TIGRE#74]
## Expected Behavior
The head phantom should rotate around the Z-axis.

## Actual Behavior

The head phantom rotate arbitratily. 

![demo5projections](https://user-images.githubusercontent.com/7495679/38164186-0ab24920-3533-11e8-8857-0380c54db384.gif)

## Code to reproduce the problem (If applicable)

```

```

## Specifications 

  - MATLAB version:
  - OS:
  - CUDA version:

**Comment by AnderBiguri** [comment]
Hi @dyycy ,

Indeed there is some bug due to bad colormap limits and other stuff.
However, I have not been able to reproduce the arbitrary "crazy" rotation that you show here. 
I have update the demo, try now, and if the error persist, make sure to recompile, and try again. If it still persist, please post here the full code so I can copy-paste it and run it.

Ander

**Comment by dyycy** [comment]
Finnally, after complied for more than 10 times, it works correctly now. 
It's really odd.
I think it relates to the CUDA compliation, which often works in a no-one-why way.

Anyway, thanks Ander. This toolkit has helped me a lot.

**Comment by AnderBiguri** [comment]
@dyycy hum that is indeed strange, but I'm glad it works! Please do not hesitate to write me for any other questions or problem you may have, and thanks for reporting this one.
Ander
